### ISSUE TITLE
Implement `ComponentValidationService`

### ISSUE THREAD

**Issue by Habiba67y** [sulton-max/Training.TruckWorld.Clone#13]
###Implement `ComponentValidationService`

###Description
Validation service checks informations of component that is being sold

Requirements
-Validate general information (properties) of Component model for CRUD
-Should inform user if properties are invalid

Deliverables
-service that validate Component
 model

**Comment by mavlonbekcoding** [comment]
Salom Xayrli kech.Yaxshimisiz.Issue'ni push qildim.

**Comment by Habiba67y** [comment]
Assalomu alaykum, pull request tashlang

**Comment by mavlonbekcoding** [comment]
Vaalykum assalom, ok.


‪ср, 27 сент. 2023 г. в 06:13, ‫حَبِيبَةُ بِنْتُ شُهْرَتِ‬‎ <
***@***.***>:‬
